### ISSUE TITLE
f-string: unmatched '['

### ISSUE THREAD

**Issue by RONNYKHALIL** [JaredTherriault/ComfyUI-JNodes#5]
I get this error when installed on my Runpod setup:

Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-JNodes/__init__.py", line 7, in <module>
    from .py.server_backend import *
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-JNodes/py/server_backend.py", line 268
    headers={"Content-Disposition": f"filename=\"{result["payload"]["filename"]}\""})
                                                          ^^^^^^^
SyntaxError: f-string: unmatched '['

any ideas around it?

**Comment by alessandroperilli** [comment]
Same

**Comment by JaredTherriault** [comment]
Thanks for your report! I submitted a fix yesterday that should have sorted this. Can you pull latest and retry?
