### ISSUE TITLE
ComfyUI-JNodes (IMPORT FAILED)

### ISSUE THREAD

**Issue by AyoKeito** [JaredTherriault/ComfyUI-JNodes#8]
Nodes don't work since one of the latest updates:
```
Traceback (most recent call last):
  File "Q:\ComfyUI-venv\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "Q:\ComfyUI-venv\ComfyUI\custom_nodes\ComfyUI-JNodes\__init__.py", line 4, in <module>
    from .py.media_nodes import *
  File "Q:\ComfyUI-venv\ComfyUI\custom_nodes\ComfyUI-JNodes\py\media_nodes.py", line 549
    f"{input_type}/{(f"{root}/{subdir}").replace(
                                      ^
SyntaxError: unterminated string literal (detected at line 549)

Cannot import Q:\ComfyUI-venv\ComfyUI\custom_nodes\ComfyUI-JNodes module for custom nodes: unterminated string literal (detected at line 549) (media_nodes.py, line 549)
```
Installation via git clone

**Comment by JaredTherriault** [comment]
Hey, thanks for the report and the logs! I missed this because I didn't have any files with special characters int he name. I have pushed an update that should resolve this. Can you give it a try?

**Comment by AyoKeito** [comment]
It's fixed now, thanks!

**Comment by JaredTherriault** [comment]
Thanks for the report! 👏👏
